[package]
name = "bike_scrape"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9.5"
reqwest = { version = "0.11.20", features = ["cookies", "native-tls"] }
tokio = { version = "1", features = ["full"] }
